name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for submitting your first issue. We appreciate that you have taken the time to inform us about it. Please just wait and relax and we will get to this issue when we can."
        pr-message: "Thanks for your first ever pull request with Pathway to Hope. We will get to this pull request when we can. "
